### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by emberian** [mbrt/ruplicity-console#6]
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback, and has protections from
patent trolls and an explicit contribution licensing clause. However, the
Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as
MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and
doing so would be wise for this project. This also makes this crate suitable
for inclusion in the Rust standard distribution and other project using dual
MIT/Apache.
# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright) and then add the following to
your README:

```
## License

Licensed under either of
 * Apache License, Version 2.0 ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)
at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, use the following boilerplate (based on that used in Rust):

```
// Copyright (c) 2015 t developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
```

And don't forget to update the `license` metadata in your `Cargo.toml`!
# Contributor checkoff
- [ ] @mbrt

**Comment by mbrt** [comment]
Currently I want that this crate keeps GPL license for the following reasons:
- The core functionality is already licensed under MIT, because it is exposed trough [ruplicity](https://github.com/mbrt/ruplicity) crate.
- This crate however provides a "product", and not a library, so I don't want anyone to fork it and close the sources (it could be possible with MIT license). Anyone is still free to use, contribute and modify it in whatever form they want. The only restriction is that they cannot change the license or integrate it in non-GPL projects;
- There is no reason in integrate this crate into the standard distribution, since this is not a library but an executable, and I don't think it is useful for everyone.

So, I'm going to close this.

**Comment by emberian** [comment]
I'm not even sure why my script picked up this crate, since the license isn't MIT or Apache-2.0 (which is explicitly what I was targetting).

Thank you for using the GPL!

**Comment by mbrt** [comment]
Probably because it started as MIT and then it became GPL. No problem!
